# Generated by Django 3.2.25 on 2024-10-01 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0003_product_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('rating', models.IntegerField(choices=[(0, '1 - Very Unsatisfied'), (1, '2 - Unsatisfied'), (2, '3 - Satisfied'), (3, '4 - Very Satisfied'), (4, '5 - Extremely Satisfied')], default=2)),
                ('ease_of_use', models.IntegerField(choices=[(0, '1 - Very Hard'), (1, '2 - Hard'), (2, '3 - Not Easy or Hard'), (3, '4 - Easy'), (4, '5 - Very Easy')], default=2)),
                ('energy_efficency', models.IntegerField(choices=[(0, '1 - Very Inefficient'), (1, '2 - Inefficient'), (2, '3 - Neither'), (3, '4 - Efficient'), (4, '5 - Very Efficient')], default=2)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_author', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
